spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    datasource:
      driver-class: org.postgresql.Driver
      url: jdbc:postgresql://postgres/postgres
      username: postgres
      password: postgres

server:
  port: 8000
